name = "react-auth"
compatibility_date = "2024-01-01"

[assets]
directory = "build"

[assets.routes]
"/*" = "index.html"
"/static/*" = "/static/*"
"/manifest.json" = "/manifest.json"
"/favicon.ico" = "/favicon.ico"
"/asset-manifest.json" = "/asset-manifest.json"
"/robots.txt" = "/robots.txt"
"/logo192.png" = "/logo192.png"
"/logo512.png" = "/logo512.png"